version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '[%(asctime)s] (%(name)20s) [%(levelname)8s] - %(message)s '
    datefmt: '%Y-%m-%d %H:%M:%S'
  complex:
    format: '[%(asctime)s] (%(name)20s:%(lineno)4s) [%(levelname)8s] - %(message)s '
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: complex
    filename: logs/antenna.log
    mode: a
    maxBytes: 10485760
    backupCount: 20
root:
  level: NOTSET
  handlers: [console, debug]
